const Task = require('../models/Task');
const WorkingOrder = require('../models/WorkingOrder');
const User = require('../models/User');

const taskController = {
  // Create task for an order
// Create task for an order
async createTask(req, res) {
  try {
    const { orderId, assignedTo, taskType, priority, schedule, notes } = req.body;
    
    // Validate required fields
    if (!orderId) {
      return res.status(400).json({ error: 'Order ID is required' });
    }
    if (!assignedTo) {
      return res.status(400).json({ error: 'Staff assignment is required' });
    }
    if (!schedule?.startDate) {
      return res.status(400).json({ error: 'Start date is required' });
    }

    // Get order details
    const order = await WorkingOrder.findById(orderId).populate('customer');
    if (!order) {
      return res.status(404).json({ error: 'Order not found' });
    }

    // Get staff details
    const staff = await User.findById(assignedTo);
    if (!staff) {
      return res.status(404).json({ error: 'Staff member not found' });
    }

    // Calculate end date
    const endDate = schedule?.endDate 
      ? new Date(schedule.endDate) 
      : new Date(new Date(schedule.startDate).getTime() + (order.duration?.days || 1) * 24 * 60 * 60 * 1000);

    // Create task (taskNumber will be auto-generated by schema default)
    const taskData = {
      order: orderId,
      assignedTo,
      assignedBy: req.userId,
      taskType: taskType || 'installation',
      priority: priority || 'medium',
      title: `Task for Order ${order.orderNumber}`,
      description: notes || `Work on order ${order.orderNumber}`,
      schedule: {
        startDate: new Date(schedule.startDate),
        endDate: endDate
      }
    };

    const task = new Task(taskData);
    await task.save();

    // Update order status
    if (!order.assignedStaff) {
      order.assignedStaff = [];
    }
    order.assignedStaff.push({
      staff: assignedTo,
      role: 'technician',
      assignedAt: new Date()
    });
    order.status = 'assigned';
    await order.save();

    res.status(201).json({
      success: true,
      message: 'Task created successfully',
      task: {
        id: task._id,
        taskNumber: task.taskNumber,
        title: task.title,
        status: task.status,
        assignedTo: {
          name: `${staff.firstName || ''} ${staff.lastName || ''}`.trim(),
          email: staff.email
        }
      }
    });

  } catch (error) {
    if (error.name === 'ValidationError') {
      const errors = {};
      for (let field in error.errors) {
        errors[field] = error.errors[field].message;
      }
      return res.status(400).json({ 
        error: 'Validation error', 
        details: errors 
      });
    }
    
    res.status(500).json({ 
      error: 'Failed to create task',
      message: error.message 
    });
  }
},
  // Get all tasks (admin/staff)
  async getAllTasks(req, res) {
    try {
      const { status, priority, page = 1, limit = 10 } = req.query;
      const query = {};

      if (status) query.status = status;
      if (priority) query.priority = priority;

      const skip = (page - 1) * limit;

      const tasks = await Task.find(query)
        .populate('assignedTo', 'firstName lastName email')
        .populate('assignedBy', 'firstName lastName')
        .populate('order', 'orderNumber ledType squareMeters')
        .sort({ createdAt: -1 })
        .skip(skip)
        .limit(parseInt(limit));

      const total = await Task.countDocuments(query);

      res.json({
        tasks,
        pagination: {
          total,
          page: parseInt(page),
          pages: Math.ceil(total / limit)
        }
      });
    } catch (error) {
      console.error('Error fetching tasks:', error.message);
      res.status(500).json({ error: error.message });
    }
  },

  // Get tasks for logged-in staff
  async getMyTasks(req, res) {
    try {
      const tasks = await Task.find({ assignedTo: req.userId })
        .populate('order', 'orderNumber ledType location programDate')
        .populate('assignedBy', 'firstName lastName')
        .sort({ createdAt: -1 });

      res.json(tasks);
    } catch (error) {
      console.error('Error fetching my tasks:', error.message);
      res.status(500).json({ error: error.message });
    }
  },

  // Get single task
  async getTaskById(req, res) {
    try {
      const task = await Task.findById(req.params.id)
        .populate('assignedTo', 'firstName lastName email phone')
        .populate('assignedBy', 'firstName lastName')
        .populate('order')
        .populate('issues.reportedBy', 'firstName lastName');

      if (!task) {
        return res.status(404).json({ error: 'Task not found' });
      }

      // Check authorization
      if (req.user.role === 'staff' && task.assignedTo._id.toString() !== req.userId) {
        return res.status(403).json({ error: 'Access denied' });
      }

      res.json(task);
    } catch (error) {
      console.error('Error fetching task:', error.message);
      res.status(500).json({ error: error.message });
    }
  },

  // Update task status (staff)
  async updateTaskStatus(req, res) {
    try {
      const { status, progress, notes } = req.body;
      const task = await Task.findById(req.params.id);

      if (!task) {
        return res.status(404).json({ error: 'Task not found' });
      }

      // Check if staff is assigned to this task
      if (req.user.role === 'staff' && task.assignedTo.toString() !== req.userId) {
        return res.status(403).json({ error: 'Access denied' });
      }

      // Update task
      task.status = status || task.status;
      if (progress !== undefined) task.progress = progress;
      if (notes) task.completionNotes = notes;

      if (status === 'completed') {
        task.completedAt = new Date();
        task.progress = 100;
      }

      await task.save();

      // Update order status if task is completed
      if (status === 'completed') {
        const order = await WorkingOrder.findById(task.order);
        if (order) {
          order.status = 'completed';
          await order.save();
        }
      }

      res.json(task);
    } catch (error) {
      console.error('Error updating task:', error.message);
      res.status(500).json({ error: error.message });
    }
  },

  // Upload completion photos
  async uploadCompletionPhotos(req, res) {
    try {
      const task = await Task.findById(req.params.id);

      if (!task) {
        return res.status(404).json({ error: 'Task not found' });
      }

      // Check if staff is assigned to this task
      if (req.user.role === 'staff' && task.assignedTo.toString() !== req.userId) {
        return res.status(403).json({ error: 'Access denied' });
      }

      if (!req.files || req.files.length === 0) {
        return res.status(400).json({ error: 'No photos uploaded' });
      }

      const photos = req.files.map(file => ({
        url: file.path,
        publicId: file.filename,
        caption: req.body.caption || ''
      }));

      task.completionPhotos.push(...photos);
      await task.save();

      res.json({
        success: true,
        message: 'Photos uploaded successfully',
        photos: task.completionPhotos
      });
    } catch (error) {
      console.error('Error uploading photos:', error.message);
      res.status(500).json({ error: error.message });
    }
  },

  // Get today's tasks for staff
  async getTodaysTasks(req, res) {
    try {
      const today = new Date();
      today.setHours(0, 0, 0, 0);
      const tomorrow = new Date(today);
      tomorrow.setDate(tomorrow.getDate() + 1);

      const tasks = await Task.find({
        assignedTo: req.userId,
        'schedule.startDate': {
          $gte: today,
          $lt: tomorrow
        }
      }).populate('order', 'orderNumber location');

      res.json(tasks);
    } catch (error) {
      console.error('Error fetching today\'s tasks:', error.message);
      res.status(500).json({ error: error.message });
    }
  },

  // Report issue with task
  async reportIssue(req, res) {
    try {
      const { description, severity } = req.body;
      const task = await Task.findById(req.params.id);

      if (!task) {
        return res.status(404).json({ error: 'Task not found' });
      }

      task.issues.push({
        reportedBy: req.userId,
        description,
        severity: severity || 'medium',
        status: 'open'
      });

      await task.save();

      res.json({
        success: true,
        message: 'Issue reported successfully',
        issues: task.issues
      });
    } catch (error) {
      console.error('Error reporting issue:', error.message);
      res.status(500).json({ error: error.message });
    }
  },

  // Resolve issue
  async resolveIssue(req, res) {
    try {
      const { issueId, resolution } = req.body;
      const task = await Task.findById(req.params.id);

      if (!task) {
        return res.status(404).json({ error: 'Task not found' });
      }

      const issue = task.issues.id(issueId);
      if (!issue) {
        return res.status(404).json({ error: 'Issue not found' });
      }

      issue.status = 'resolved';
      issue.resolvedAt = new Date();
      issue.resolution = resolution;

      await task.save();

      res.json({
        success: true,
        message: 'Issue resolved successfully',
        issue
      });
    } catch (error) {
      console.error('Error resolving issue:', error.message);
      res.status(500).json({ error: error.message });
    }
  }
};

module.exports = taskController;
